export function testData() {
  return [
    {
      logId: 6389969899346115000,
      activityTypeId: 90009,
      activityName: "Run",
      calories: 331,
      distance: 3.51193,
      steps: 3140,
      speed: 10.09820127795527,
      pace: 356.4991329553835,
      averageHeartRate: 164,
      duration: 1257000,
      activeDuration: 1252000,
      activityLevel: [
        {
          minutes: 0,
          name: "sedentary",
        },
        {
          minutes: 0,
          name: "lightly",
        },
        {
          minutes: 0,
          name: "fairly",
        },
        {
          minutes: 21,
          name: "very",
        },
      ],
      distanceUnit: "Kilometer",
      source: {
        type: "tracker",
        name: "Inspire 3",
        id: "E1D82A22963F",
        url: "https://www.fitbit.com/",
        trackerFeatures: [
          "DISTANCE",
          "STEPS",
          "GPS",
          "PACE",
          "CALORIES",
          "HEARTRATE",
          "VO2_MAX",
        ],
      },
      logType: "tracker",
      manualValuesSpecified: {
        calories: false,
        distance: false,
        steps: false,
      },
      intervalWorkoutData: {
        intervalSummaries: [],
        numRepeats: 0,
      },
      heartRateZones: [
        {
          minutes: 0,
          caloriesOut: 13.149897,
          name: "Out of Range",
          min: 30,
          max: 112,
        },
        {
          minutes: 1,
          caloriesOut: 14.191473,
          name: "Fat Burn",
          min: 113,
          max: 139,
        },
        {
          minutes: 12,
          caloriesOut: 188.65344,
          name: "Cardio",
          min: 140,
          max: 172,
        },
        {
          minutes: 8,
          caloriesOut: 115.22291,
          name: "Peak",
          min: 173,
          max: 220,
        },
      ],
      activeZoneMinutes: {
        totalMinutes: 21,
        minutesInHeartRateZones: [
          {
            minutes: 0,
            zoneName: "Out of Range",
            order: 0,
            type: "OUT_OF_ZONE",
            minuteMultiplier: 0,
          },
          {
            minutes: 1,
            zoneName: "Fat Burn",
            order: 1,
            type: "FAT_BURN",
            minuteMultiplier: 1,
          },
          {
            minutes: 12,
            zoneName: "Cardio",
            order: 2,
            type: "CARDIO",
            minuteMultiplier: 2,
          },
          {
            minutes: 8,
            zoneName: "Peak",
            order: 3,
            type: "PEAK",
            minuteMultiplier: 2,
          },
        ],
      },
      inProgress: false,
      caloriesLink:
        "https://api.fitbit.com/1/user/-/activities/calories/date/2024-12-09/2024-12-09/1min/time/9:25/9:46.json",
      heartRateLink:
        "https://api.fitbit.com/1/user/-/activities/heart/date/2024-12-09/2024-12-09/1sec/time/9:25:28/9:46:25.json",
      tcxLink:
        "https://api.fitbit.com/1/user/-/activities/6389969899346114680.tcx",
      lastModified: "2024-12-08T22:49:02.003Z",
      startTime: "2024-12-09T09:25:28.000+11:00",
      originalStartTime: "2024-12-09T09:25:28.000+11:00",
      originalDuration: 1257000,
      elevationGain: 0,
      hasActiveZoneMinutes: true,
    },
    {
      logId: 2128703669839613200,
      activityTypeId: 90009,
      activityName: "Run",
      calories: 178,
      distance: 1.8217,
      steps: 1649,
      speed: 9.906525679758309,
      pace: 363.3968271394851,
      averageHeartRate: 167,
      duration: 985000,
      activeDuration: 662000,
      activityLevel: [
        {
          minutes: 0,
          name: "sedentary",
        },
        {
          minutes: 0,
          name: "lightly",
        },
        {
          minutes: 0,
          name: "fairly",
        },
        {
          minutes: 12,
          name: "very",
        },
      ],
      distanceUnit: "Kilometer",
      source: {
        type: "tracker",
        name: "Inspire 3",
        id: "E1D82A22963F",
        url: "https://www.fitbit.com/",
        trackerFeatures: [
          "DISTANCE",
          "STEPS",
          "GPS",
          "PACE",
          "CALORIES",
          "HEARTRATE",
          "VO2_MAX",
        ],
      },
      logType: "tracker",
      manualValuesSpecified: {
        calories: false,
        distance: false,
        steps: false,
      },
      intervalWorkoutData: {
        intervalSummaries: [],
        numRepeats: 0,
      },
      heartRateZones: [
        {
          minutes: 0,
          caloriesOut: 15.01141,
          name: "Out of Range",
          min: 30,
          max: 110,
        },
        {
          minutes: 1,
          caloriesOut: 15.01141,
          name: "Fat Burn",
          min: 111,
          max: 137,
        },
        {
          minutes: 11,
          caloriesOut: 165.647076,
          name: "Cardio",
          min: 138,
          max: 171,
        },
        {
          minutes: 5,
          caloriesOut: 69.835556,
          name: "Peak",
          min: 172,
          max: 220,
        },
      ],
      activeZoneMinutes: {
        totalMinutes: 17,
        minutesInHeartRateZones: [
          {
            minutes: 0,
            zoneName: "Out of Range",
            order: 0,
            type: "OUT_OF_ZONE",
            minuteMultiplier: 0,
          },
          {
            minutes: 1,
            zoneName: "Fat Burn",
            order: 1,
            type: "FAT_BURN",
            minuteMultiplier: 1,
          },
          {
            minutes: 11,
            zoneName: "Cardio",
            order: 2,
            type: "CARDIO",
            minuteMultiplier: 2,
          },
          {
            minutes: 5,
            zoneName: "Peak",
            order: 3,
            type: "PEAK",
            minuteMultiplier: 2,
          },
        ],
      },
      inProgress: false,
      caloriesLink:
        "https://api.fitbit.com/1/user/-/activities/calories/date/2024-12-04/2024-12-04/1min/time/18:54/19:11.json",
      heartRateLink:
        "https://api.fitbit.com/1/user/-/activities/heart/date/2024-12-04/2024-12-04/1sec/time/18:54:39/19:11:04.json",
      tcxLink:
        "https://api.fitbit.com/1/user/-/activities/2128703669839613272.tcx",
      lastModified: "2024-12-04T08:57:17.900Z",
      startTime: "2024-12-04T18:54:39.000+11:00",
      originalStartTime: "2024-12-04T18:54:39.000+11:00",
      originalDuration: 985000,
      elevationGain: 0,
      hasActiveZoneMinutes: true,
    },
    {
      logId: 2474517443734024000,
      activityTypeId: 90009,
      activityName: "Run",
      calories: 265,
      distance: 2.54427,
      steps: 2276,
      speed: 9.977529411764706,
      pace: 360.81076300864294,
      averageHeartRate: 177,
      duration: 920000,
      activeDuration: 918000,
      activityLevel: [
        {
          minutes: 0,
          name: "sedentary",
        },
        {
          minutes: 0,
          name: "lightly",
        },
        {
          minutes: 0,
          name: "fairly",
        },
        {
          minutes: 15,
          name: "very",
        },
      ],
      distanceUnit: "Kilometer",
      source: {
        type: "tracker",
        name: "Inspire 3",
        id: "E1D82A22963F",
        url: "https://www.fitbit.com/",
        trackerFeatures: [
          "DISTANCE",
          "STEPS",
          "GPS",
          "PACE",
          "CALORIES",
          "HEARTRATE",
          "VO2_MAX",
        ],
      },
      logType: "tracker",
      manualValuesSpecified: {
        calories: false,
        distance: false,
        steps: false,
      },
      intervalWorkoutData: {
        intervalSummaries: [],
        numRepeats: 0,
      },
      heartRateZones: [
        {
          minutes: 0,
          caloriesOut: 15.047635,
          name: "Out of Range",
          min: 30,
          max: 114,
        },
        {
          minutes: 1,
          caloriesOut: 16.356125,
          name: "Fat Burn",
          min: 115,
          max: 140,
        },
        {
          minutes: 3,
          caloriesOut: 53.517382,
          name: "Cardio",
          min: 141,
          max: 172,
        },
        {
          minutes: 11,
          caloriesOut: 180.703165,
          name: "Peak",
          min: 173,
          max: 220,
        },
      ],
      activeZoneMinutes: {
        totalMinutes: 15,
        minutesInHeartRateZones: [
          {
            minutes: 0,
            zoneName: "Out of Range",
            order: 0,
            type: "OUT_OF_ZONE",
            minuteMultiplier: 0,
          },
          {
            minutes: 1,
            zoneName: "Fat Burn",
            order: 1,
            type: "FAT_BURN",
            minuteMultiplier: 1,
          },
          {
            minutes: 3,
            zoneName: "Cardio",
            order: 2,
            type: "CARDIO",
            minuteMultiplier: 2,
          },
          {
            minutes: 11,
            zoneName: "Peak",
            order: 3,
            type: "PEAK",
            minuteMultiplier: 2,
          },
        ],
      },
      inProgress: false,
      caloriesLink:
        "https://api.fitbit.com/1/user/-/activities/calories/date/2024-12-01/2024-12-01/1min/time/12:30/12:45.json",
      heartRateLink:
        "https://api.fitbit.com/1/user/-/activities/heart/date/2024-12-01/2024-12-01/1sec/time/12:30:28/12:45:48.json",
      tcxLink:
        "https://api.fitbit.com/1/user/-/activities/2474517443734024400.tcx",
      lastModified: "2024-12-01T01:47:59.428Z",
      startTime: "2024-12-01T12:30:28.000+11:00",
      originalStartTime: "2024-12-01T12:30:28.000+11:00",
      originalDuration: 920000,
      elevationGain: 0,
      hasActiveZoneMinutes: true,
    },
  ];
}
